window.puraneTrackFiles = [
    "90\u0027s Love Song  Is Dil Mein Kya Hai  Jab Pyaar Kisise Hota Hai  Lata Mangeshkar, Udit Narayan.mp3",
    "90s Romantic Song  Madhosh Dil Ki Dhadkan  Lata Mangeshkar  Salman Khan  Twinkle Khanna.mp3",
    "Aa Jaana Aa jaana  Coolie No. 1  Govinda \u0026 Karisma Kapoor  Kumar Sanu \u0026 Alka Yagnik  90\u0027s Hits.mp3",
    "Aaja Aaja Yaad Sataye - Video Song  Raja Babu  Govinda \u0026 Karishma Kapoor  Tips Official.mp3",
    "Aaja Mahiya Song Video - Fiza - Hrithik Roshan, Neha.mp3",
    "Aana Mere Pyar Ko Full Video - Kabhi Haan Kabhi NaaShah Rukh Khan,SuchitraAlka Yagnik.mp3",
    "Aankhon Mein Base Ho Tum (Duet)  Sunil Shetty  Sonali Bendre  Takkar  Bollywood Songs  Abhijeet.mp3",
    "Aati Kya Khandala  Ghulam  Aamir Khan \u0026 Rani Mukherjee  Alka Yagnik  90\u0027s Best Hindi Songs.mp3",
    "Aaye Ho Meri Zindagi Mein (Male)  Aamir, Karisma  Udit Narayan  Raja Hindustani  90\u0027s Hit Hindi.mp3",
    "Ab Tere Dil Mein Hum Aa Gaye -4K  Kumar Sanu, Alka Yagnik  Akshay Kumar, Madhuri Dixit  Aarzoo.mp3",
    "Abhi Saans Lene Ki Fursat Nahin - Jeet  Salman Khan \u0026 Karisma Kapoor  Sonu Nigam \u0026 Alka Yagnik.mp3",
    "Ae Kash Ke Hum Full Video - Kabhi Haan Kabhi NaaShah Rukh Khan,SuchitraKumar Sanu.mp3",
    "Ae Mere Humsafar Full Video Song  Baazigar  Shahrukh Khan, Kajol  Vinod Rathod \u0026 Alka Yagnik.mp3",
    "Aisa Deewana Lyrical Video Song  Dil Maange More  Sonu Nigam  Himesh RShahid Kapoor, Tulip Joshi.mp3",
    "Andekhi Anjaani  Full Song  Mujhse Dosti Karoge  Hrithik Roshan, Kareena Kapoor, Rani Mukerji.mp3",
    "Are Re Are - Full Song  Dil To Pagal Hai  Shah Rukh Khan  Madhuri Dixit  Lata  Udit Narayan.mp3",
    "Aye Dil Laya Hai Bahaar - Video Song  Kya Kehna  Preity Zinta  Kavita Krishnamurthy \u0026 Hariharan.mp3",
    "Baazigar O Baazigar Full Video Song  Baazigar  Shahrukh Khan, Kajol  Kumar Sanu \u0026 Alka Yagnik.mp3",
    "Chaahat Na Hoti  Alka Yagnik, Vinod Rathod  Chaahat  Shah Rukh Khan, Pooja Bhatt.mp3",
    "Chaha Toh Bahut Full Video - Imtihan  Saif Ali Khan \u0026 Raveena Tandon  Kumar Sanu \u0026 Bela.mp3",
    "Chain Aap Ko (HD) Full Video Song  Hungama  Akshaye Khanna, Rimi Sen, Paresh Rawal.mp3",
    "Chalte Chalte  Full Song  Mohabbatein  Shah Rukh Khan, Uday Chopra, Jugal Hansraj, Jimmy Shergill.mp3",
    "Chamma Chamma  90\u0027s Popular Song  Urmila Matondkar  Alka Yagnik  China - Gate  90\u0027s Item Song.mp3",
    "Chand Se Parda Keejiye - Aao Pyaar Karen  Saif Ali Khan \u0026 Shilpa Shetty  Kumar Sanu Romantic Song.mp3",
    "Chand Sitare Phool Aur Khushboo Song Kaho Naa Pyaar Hai  Hrithik Roshan  Ameesha P  Kumar Sanu.mp3",
    "Chand Tare Tod Full Video Song  Yes Boss  Shahrukh Khan, Juhi Chawla  Abhijeet.mp3",
    "Chehra Kya Dekhte Ho Full Video Song  Salaami  Kumar Sanu \u0026 Asha Bhosle  Ayub Khan \u0026 Samyukta.mp3",
    "Chhoti Chhoti Raatein (Full Song) Film - Tum Bin... Love Will Find A Way.mp3",
    "Chhupana Bhi Nahin Aata Full Video Song  Baazigar  Shahrukh Khan, Kajol  Vinod Rathod.mp3",
    "Chunnari Chunnari  Salman Khan \u0026 Sushmita Sen  Anu Malik  Biwi No 1  90\u0027s Blockbuster Hindi Song.mp3",
    "Chura Ke Dil Mera - 4K VIDEO  Akshay \u0026 Shilpa  Main Khiladi Tu Anari  Kumar Sanu \u0026 Alka Yagnik.mp3",
    "Dance Masti  Official Video Instant Karma  Shaan  Naveeda Mehdi.mp3",
    "Deewana Hai Ye Mann  Chori Chori Chupke Chupke(2001) Song  Salman Khan  Rani Mukherjee #4kvideo (1).mp3",
    "Deewana Hai Ye Mann  Chori Chori Chupke Chupke(2001) Song  Salman Khan  Rani Mukherjee #4kvideo.mp3",
    "Deewana Main Tera Deewana Full Video - English Babu Desi Mem  Shahrukh Khan, Sonali Bendre.mp3",
    "Dekho Dekho Jaanam Full Video - IshqAjay Devgan,KajolUdit NarayanAlka Yagnik,Anu Malik.mp3",
    "Dheere Dheere Se Meri Zindagi Mein Aana Full Video Song  Aashiqui  Kumar Sanu, Anuradha Paudwal.mp3",
    "Dholna  Full Song  Dil To Pagal Hai  Shah Rukh Khan, Madhuri Dixit, Lata Mangeshkar, Udit Narayan.mp3",
    "Didi Tera Devar Deewana - Hum Aapke Hain Koun - Salman Khan, Madhuri Dixit - Best Bollywood Song.mp3",
    "Dil Deewana   Maine Pyar Kiya  Salman Khan \u0026 Bhagyashree  Classic Romantic Old Hindi Song.mp3",
    "Dil Ka Aalam - All Time Hit Indian Song From Aashiqui  Kumar Sanu.mp3",
    "Dil Ka Aalam [Full Song]  Aashiqui  KUMAR SANU.mp3",
    "Dil Ke Badle Sanam (Full Song) Film - Kyon Ki ...It\u0027S Fate.mp3",
    "Dil Kehta Hai   Akele Hum Akele Tum  Kumar Sanu \u0026 Alka Yagnik  Aamir Khan #romanticsong.mp3",
    "Dil Ki Tanhai Ko  Kumar Sanu  Chaahat  Shah Rukh Khan, Ramya Krishnan, Pooja Bhatt.mp3",
    "Dil Ko Tumse Pyar Hua - Rehna Hai Tere Dil Mein.mp3",
    "Dil Laga Liya - Full Video  Dil Hai Tumhaara  Preity \u0026 Arjun Rampal  Alka Yagnik \u0026 Udit Narayan.mp3",
    "Dil Mera Tod Diya (Full 4K Video Song)  Alka Yagnik  Kasoor Movie.mp3",
    "Dil Pardesi Ho Gaya - Lyrical  Kachche Dhaage  Lata Mangeshkar  Kumar S  Ajay Devgn  Manisha K.mp3",
    "Dil To Pagal Hai Song  Shah Rukh Khan, Madhuri Dixit, Karisma Kapoor, Akshay Kumar, Lata Mangeshkar.mp3",
    "Dil To Pagal Hai Song  Shah Rukh Khan, Madhuri, Karisma, Akshay  Lata Mangeshkar, Udit Narayan.mp3",
    "Do Lafzo Mein [Full Song] Dhaai Akshar Prem Ke Ft Aishwarya Rai, Abhishek Bacchan.mp3",
    "Duniya Mein Aaye  Salman Khan  Rambha  Judwaa Songs  Kumar Sanu  Kavita Krishnamurthy.mp3",
    "Ek Ladki Ko Dekha to-HD.mp3",
    "Falguni Pathak - Chudi.mp3",
    "Falguni Pathak - Maine Payal Hai Chhankai.mp3",
    "Falguni Pathak - Meri Chunar Udd Udd Jaye.mp3",
    "Full Song_ Pehli Pehli Baar Jab  Jab Pyaar Kisise Hota Hai  Salman Khan  Kumar Sanu  90s Song.mp3",
    "Full Video_ Har Dil Jo Pyar Karega Title Song Salman Khan,Rani Mukherjee Udit Narayan, Alka Yagnik.mp3",
    "Ghoongte Mein Chanda Hai - Koyla - Shahrukh Khan \u0026 Madhuri Dixit.mp3",
    "Gore Gore Mukhde Pe Kala Kala Chasma Song  Akshay Kumar  Suhaag  90\u0027s Songs  Udit Narayan, Alka.mp3",
    "Gup Chup Gup Chup  Karan Arjun  Mamta Kulkarni  Alka Yagnik  Mujhko Ranaji Maaf Karna  90\u0027s.mp3",
    "Hamne Tumko Dil Ye De Diya Full Video - GunaahDino, BipashaAlka Yagnik,Babul Supriyo.mp3",
    "Ho Nahin Sakta Full Video Song  Diljale  Udit Narayan  Anu Malik  Ajay Devgn, Sonali Bendre (1).mp3",
    "Ho Nahin Sakta Full Video Song  Diljale  Udit Narayan  Anu Malik  Ajay Devgn, Sonali Bendre.mp3",
    "Ho Sarkay Leo Khattiya Jaada Lage - Raja Babu - Govinda, Karisma Kapoor.mp3",
    "Hothon Pe Bas  Full Song  Yeh Dillagi  Saif Ali Khan  Kajol  Lata Mangeshkar  Kumar Sanu.mp3",
    "Hum Pyaar Hai Tumhare - Lyrical  Haan Maine Bhi Pyaar Kiya  Kumar Sanu, Alka Yagnik  Love Songs.mp3",
    "Hum Teri Mohabbat Mein  Phool Aur Angaar Songs  Mithun Chakraborty, Shanti Priya  Kumar Sanu.mp3",
    "Hum To Tujhse Mohabbat 4K  Akshay Kumar \u0026 Raveena Best Romantic Song  Kumar Sanu \u0026 Alka Yagnik.mp3",
    "Husn Hai Suhana  Coolie No. 1  Govinda \u0026 Karisma Kapoor  Abhijeet \u0026 Chandana Dixit  90\u0027s Hits.mp3",
    "Is Pyar Se Meri Taraf Na Dekho  Kumar Sanu, Alka Yagnik  Chamatkar  Shah Rukh Khan.mp3",
    "Is Tarah Aashiqui Ka  Imtihan  Saif Ali Khan, Raveena, Sunny Deol  Kumar Sanu  90\u0027s Hindi Songs.mp3",
    "Is Tarah Aashiqui Ka  Imtihan  Saif, Raveena, Sunny Deol  Amit Kumar  Anu Malik  90s Hindi Hits.mp3",
    "Jaadu Teri Nazar Song  Darr  Shah Rukh Khan, Juhi Chawla  Udit Narayan  Shiv-Hari  Anand Bakshi.mp3",
    "Jaane Dil Mein - Full Song  Mujhse Dosti Karoge  Hrithik Roshan, Rani, Lata Mangeshkar, Sonu Nigam.mp3",
    "Jaati Hoon Main Jaldi Hai Kya  Karan Arjun  Shah Rukh Khan, Kajol  Kumar Sanu, Alka Yagnik  90\u0027s (1).mp3",
    "Jaati Hoon Main Jaldi Hai Kya  Karan Arjun  Shah Rukh Khan, Kajol  Kumar Sanu, Alka Yagnik  90\u0027s.mp3",
    "Jab Pyaar kiya Toh Darna Kiya (full song) Salman Khan  Kajol.mp3",
    "Jhuki Jhuki Nazar Teri Kamaal  HD Video Song  Raja (1995) Alka Yagnik  Udit Narayan  Madhuri.mp3",
    "Jo Bhi Kasmein Khai Thi Humne - Raaz  Bipasha Basu \u0026 Dino Morea  Alka Yagnik \u0026 Udit Narayan.mp3",
    "Jo Haal Dil Ka  Aamir Khan  Sonali Bendre  Sarfarosh Movie  Alka Yagnik  Kumar Sanu  90s Hits.mp3",
    "Kab Ban Jayega Tere Kabil Mera Dil - Hai Dil  Aishwariya Rai  Alka, Kumar  Dil Ka Rishta.mp3",
    "Kaho Naa Pyaar Hai - Title Track  Hrithik Roshan \u0026 Ameesha Patel  Alka Yagnik \u0026 Udit Narayan.mp3",
    "Kaise Mukhde Se  Full Song  English Babu Desi Mem  Shah Rukh Khan, Sonali Bendre.mp3",
    "Kasam Khake Kaho  Dil Hai Tumhaara  Preity Zinta Arjun \u0026 Mahima  Alka Yagnik, Kumar Sanu.mp3",
    "Kisi Din Banoongi Main  Raja Songs  Madhuri Dixit  Sanjay Kapoor  Udit Narayan  Alka Yagnik.mp3",
    "Kisi Disco Mein Jaaye  Bade Miyan Chhote Miyan  Govinda, Raveena Tandon Alka, Y Udit N 90\u0027s Hits.mp3",
    "Kitaben Bahut Si - 4K VIDEO  Baazigar  Shah Rukh Khan \u0026 Kajol  Asha Bhosle  90\u0027s  Romantic Songs.mp3",
    "Kitna Haseen Chehra  Kumar Sanu  Dilwale 1994 Song  Ajay Devgan, Raveena Tandon.mp3",
    "Kitna Pyara Tujhe Rab Ne Banaya  Raja Hindustani  Aamir Khan, Karisma  Alka Yagnik, Udit Narayan.mp3",
    "Krrish   Bluray Video Song   1080p HD.mp3",
    "Kuch Kuch Hota Hai_ Title Track  4K Video  Shah Rukh Khan Kajol Rani Alka Yagnik Udit Narayan.mp3",
    "Ladki Badi Anjani Hai - Full VideoShah Rukh Khan,Kajol Kumar Sanu,Alka Yagnik Timeless Classics.mp3",
    "Lal Dupatta Full HD Song  Mujhse Shaadi Karogi  Salman Khan, Priyanka Chopra.mp3",
    "Le Gayi  Full Song  Dil To Pagal Hai  Shah Rukh Khan, Karisma Kapoor  Asha Bhosle, Udit Narayan.mp3",
    "Main Agar Saamne  Raaz  Dino Morea  Bipasha Basu  Abhijeet \u0026 Alka Yagnik  Hindi Hit Songs.mp3",
    "Main Duniya Bhula Doonga (Full Song)  Aashiqui  Rahul Roy, Anu Agarwal.mp3",
    "Main Ishq Uska [Full Song] Vaada  Zayed Khan, Amisha Patel  Alka Yagnik  Himesh Reshammiya.mp3",
    "Mera Dil Bhi Kitna Pagal Hai (Eng Sub) [Full Song] (HQ) With Lyrics - Saajan.mp3",
    "Mere Khwabon Mein - Full Song  Dilwale Dulhania Le Jayenge  Shah Rukh Khan  Kajol  DDLJ.mp3",
    "Meri Tarah Tum Bhi Kabhi Pyar Karke Dekho Na !! Romantic Songs.mp3",
    "Mile Tum Se Bichhad Ke Hum Full Video Song  Salaami  Ayub Khan, Samyukta  Ishtar Music.mp3",
    "Mohabbat Dil Ka Sakoon Hai Aitbaar  Dil Hai Tumhaara  Alka, Kumar \u0026 Udit  Nadeem - Shravan.mp3",
    "Mohabbat Ki Nahi Jati  Udit Narayan  Sadhana Sargam  Hero No.1  1997.mp3",
    "Mujhse Mohabbat Ka - Video Song  Hum Hain Rahi Pyaar Ke  Aamir Khan, Juhi Chawla.mp3",
    "Muqabala Muqabala - Video Song  Hum Se Hai Muqabala  Parbhu Deva  A.R.Rahman  Best Dance Song.mp3",
    "Na Kajre Ki Dhar - With Lyrics  Suniel Shetty  Pankaj Udhas \u0026 Sadhana Sargam  Mohra  90\u0027s Song.mp3",
    "O Bijuria Sun  Full Song  English Babu Desi Mem  Shah Rukh Khan, Sonali Bendre.mp3",
    "O Lal Dupatte Wali  Govinda Chunky Pandey  Rageshwari  Aankhen  Bollywood Songs.mp3",
    "O Lal Dupatte Wali - Govinda, Chunky Pandey, Rageshwari, Aankhen Song.mp3",
    "O O Jaane Jaana Full Video Song  Pyar Kiya To Darna Kya  Kamal Khan  Salman Khan, Kajol.mp3",
    "O Soniya Full Video - Ishq Hai TumseBipasha Basu, Dino MoreaUdit Narayan, Alka Yagnik.mp3",
    "Oh Oh Jane Jaana Salman Khan Full Song  Pyaar Kiya Toh Darna Kya.mp3",
    "Ole Ole Full Song  Yeh Dillagi  Saif Ali Khan, Kajol  Abhijeet Bhattacharya, Dilip Sen-Sameer Sen.mp3",
    "Paas Woh Aane Lage - 4K Video  Main Khiladi Tu Anari  Kumar Sanu \u0026 Alka Yagnik  90\u0027s Hindi Songs.mp3",
    "Pardesi Pardesi Jana Nahin  Aamir Khan, Karisma Kapoor  Sapna Awasthi  Raja Hindustani  90\u0027s Hit.mp3",
    "Pehle Kabhi Na Mera Haal - Video Song  Baghban  Udit Narayan, Alka Yagnik  Salman Khan, Mahima.mp3",
    "Pehli Baar Dil Yun - 4K Video Song  Hum Ho Gaye Aapke  Fardeen Khan  Kumar Sanu  Alka Yagnik.mp3",
    "Pehli Pehli Baar Mohabbat Ki Hai Full Video Song  Sirf TumKumar Sanu,Alka YagnikSanjay K, Priya G.mp3",
    "Phool Maangu Na Bahaar Maangu - Video Song  Raja  Madhuri Dixit \u0026 Sanjay Kapoor.mp3",
    "Piya Basanti - K.S. Chithra  Ustad Sultan Khan Official Video  Sandesh Shandilya.mp3",
    "Pucho Zara Pucho  Aamir Khan,Karisma Kapoor  Alka Yagnik,Kumar Sanu  Raja Hindustani  90\u0027s Hit.mp3",
    "Pyar Dilon Ka Mela Hai  Dulhan Hum Le Jaayenge  Salman, Karisma  Alka Yagnik, Sonu Nigam  90s.mp3",
    "Pyar Mein Dil De Diya  Anari  Karisma Kapoor, Venkatesh  Alka Yagnik, Kumar Sanu  90\u0027s Hits.mp3",
    "Raah Mein Unse Mulaqat Ho Gayi  Ajay Devgn, Tabu  Kumar Sanu, Alka Yagnik  Vijaypath (1994).mp3",
    "Rabb Kare Tujhko Bhi [Full Song] Mujhse Shaadi Karogi.mp3",
    "Raja Ko Rani Se Pyar Ho Gaya Video Song  Akele Hum Akele Tum  Aamir Khan, Manisha Koirala.mp3",
    "Ram Jaane Title Track   Udit Narayan, Sonu Nigam, Alka Yagnik  Shah Rukh Khan, Juhi Chawla (1).mp3",
    "Ruk Ja O Dil Deewane - Full Song Dilwale Dulhania Le Jayenge  Shah Rukh Khan, Kajol  Udit Narayan (1).mp3",
    "Ruk Ja O Dil Deewane - Full Song Dilwale Dulhania Le Jayenge  Shah Rukh Khan, Kajol  Udit Narayan.mp3",
    "Saari Raat Teri Yaad  Footpath  Emraan Hashmi  Udit Narayan  Alka Yagnik  Bollywood Love Song.mp3",
    "Shushmita Sen_ Dilbar Dilbar HD Video Song  Alka Yagnik  T-Series Songs.mp3",
    "Sona Kitna Sona Hai  Govinda, Karisma Kapoor  Udit N \u0026 Poornima  Hero No.1  90\u0027s Hits.mp3",
    "Suniye To - HD VIDEO  Shah Rukh Khan \u0026 Juhi Chawla  Yes Boss  90\u0027s  Song  Ishtar Regional.mp3",
    "Tamma Tamma from THANEDAAR Enhanced Video (HD).mpg.mp3",
    "Tan Tana Tan Tan Taara  Judwaa Songs  Salman Khan  Karishma Kapoor  Abhijeet  Poornima.mp3",
    "Tera Dil Mere Paas Rehne De -4K Video  #lovesong  Rimi  \u0026 Aftab S  Udit N. \u0026 Alka Y.  90\u0027s hits.mp3",
    "Tera Rang Balle Balle  Sonu Nigam  Jaspinder Narula  Soldier I Bobby  Preity Zinta I 90s Hits.mp3",
    "Tere Dar Par Sanam - Vídeo Song  Phir Teri Kahani Yaad Aayi  Pooja Bhatt, Rahul Roy  Kumar Sanu.mp3",
    "Tere Ishq Mein Nachenge  Raja Hindustani  Aamir Khan, Karisma Kapoor  Kumar Sanu, Alisha Chinai.mp3",
    "Teri Chunnariya  Hello Brother  Salman Khan  Rani Mukherjee  Kumar Sanu  Alka Yagnik.mp3",
    "Teri Mohabbat Ne Dil Mein Makaam Kar Diya  Rang  Alka Yagnik, Kumar Sanu  90\u0027s Hit Song.mp3",
    "Tu Dharti Pe Chaahe Jahan Bhi Rahegi  Jeet  Kumar Sanu, Alka Yagnik  Karisma, Sunny Deol.mp3",
    "Tu Meri Zindagi Hai (Full Song)  Aashiqui  Rahul Roy, Anu agarwal.mp3",
    "Tu Nikla Chhupa Rustam Full Song 4K _ Alka Yagnik  Mamta Kulkarni  Sanjay Kapoor  Hindi Song 90s.mp3",
    "Tu Pyar Hai Kisi Aur Ka (Full Song)_Aamir K, Pooja B Anuradha P, Kumar Sanu Dil Hai Ke Manta Nahin.mp3",
    "Tujhe Dekha Toh Song  Dilwale Dulhania Le Jayenge  Shah Rukh Khan, Kajol  Lata, Kumar Sanu  DDLJ.mp3",
    "Tum Bin Jiya Jaye Kaise Lyrical Video Song  Tum Bin  Chitra  Nikhil, Vinay  Priyanshu, Sandali.mp3",
    "Tumko Dekha To Kya Yeh Hogaya - Hamara Dil Aapke Paas Hai  Alka Yagnik, Kumar Sanu  Hindi Song.mp3",
    "Tumne Agar Pyar Se Dekha  Raja Songs  Madhuri Dixit  Sanjay Kapoor  Alka Yagnik.mp3",
    "Tumsa Koi Pyaara  Khuddar  Govinda, Karisma Kapoor  Kumar Sanu, Alka Yagnik 90s Hits Hindi Songs.mp3",
    "Tumsa Koi Pyaara  Kumar Sanu  Alka Yagnik  Khuddar (1994) (1).mp3",
    "Tumsa Koi Pyaara  Kumar Sanu  Alka Yagnik  Khuddar (1994).mp3",
    "Tumse Milne Ko Dil Karta Hai - Phool Aur Kaante      Ajay Devgn \u0026 Madhoo.mp3",
    "Tune Zindagi Mein - 4K Video Humraaz  Bobby Deol \u0026 Amisha Patel Udit Narayan Hindi Romantic Song.mp3",
    "Urvashi Urvashi  Hum Se Hai Muqabala  Prabhu Deva  A.R.Rahman.mp3",
    "Video Not Available.mp3",
    "Woh Aankh Hi Kya Teri Surat Nahi Jisme  Govinda, Karishma Kapoor  Kumar Sanu  Alka Yagnik.mp3",
    "Woh Ladki Jo Full Video Song  Baadshah  Shahrukh Khan, Twinkle Khanna  Abhijeet.mp3",
    "Yeh Bandhan Toh  Karan Arjun  Shahrukh Khan, Salman Khan  Kumar Sanu, Udit Narayan  Alka Yagnik.mp3",
    "Yeh Dua Hai Meri Rab Se - 4K Video Song  Sapne Sajan Ke  Alka Yagnik, Kumar Sanu, Karishma Kapoor.mp3",
    "Yeh Jo Teri Payalon Ki Chan Chan Hai  Abhijeet Bhattacharya  Sadhana Sargam  Masoom.mp3",
    "Yunhi Kat Jaayega Safar - Hum Hai Rahi Pyaar Ke - Aamir Khan, Juhi Chawla.mp3",
    "Zara Dekh Mera Deewanapan Ki Tere Bina Kahin Dil Na Lage  Footpath  Udit Narayan, Alka Yagnik.mp3",
    "Zara Sa Jhoom Loon Main  Full Song  Dilwale Dulhania Le Jayenge  Shah Rukh Khan, Kajol  DDLJ.mp3",
    "Zindagi Ban Gaye Ho Tum (Full 4K Video Song)  Udit Narayan, Alka Yagnik  Kasoor Movie.mp3",
    "चर चर दल तर चरयग - Chori Chori Dil Tera  Kumar Sanu  Romantic Songs - 90\u0027s Love Song.mp3",
    "सपरहट गन - Saathiya Bin Tere Dil Mane Na - 90s Sunny Deol Hit  Tabu  Kumar Sanu  Shilpa.mp3"
];
// Papa ke songs hata kar remaining Purane songs
window.remainingPuraneTrackFiles =
  window.puraneTrackFiles.filter(
    file => !file.toLowerCase().includes("90s love song")
  );

let files = window.remainingPuraneTrackFiles || [];

console.log("PURANE TOTAL:", window.puraneTrackFiles.length);
console.log("REMAINING TOTAL:", files.length);

let urls = files.map(file =>
  "tracks/purane/" + encodeURIComponent(file)
);