window.haryanviTrackFiles = [
  "2 Khatole _ MASOOM SHARMA  Manjeet Mor, Chahal Saab, Vikash Rajana  New Haryanvi Song 2024.mp3",
  "80 Lakh  Kala Dighal, Sweta Chauhan  Shiva Choudhary, D Naveen  New Haryanvi Songs Haryanavi 2026.mp3",
  "Aaja Baby Baith Seat Pe  Vikram Sarkar, Khushi Baliyan, Manisha Sharma  New Haryanvi Song 2022.mp3",
  "Aakh Ye Taalibaani (Official Video) Manish sonipat Aala  Bali Sharma  Mayuri Gahlot New Song 2025.mp3",
  "BYAH KE LAVANGE ( Feat. Sachin Jaat & Swarnima Chuhnx ) Masoom Sharma  Ashu Twinkle  Hit Music.mp3",
  "Badli Badli Laage  Sapna Chaudhary  Official Lyrical Video  Vicky Kajla  New Haryanvi Song 2026.mp3",
  "Bagdo - Dj Song  Raj Mawar  Manisha Sharma  Khushi Baliyan  Mannu Pahari New Haryanvi Song 2025.mp3",
  "Bahu Kale Ki.mp3",
  "Bairi (Official Video) Virat, Miss Parul  Pradeep Solanki, Heena  New Rajasthani Song 2026.mp3",
  "Bau Ji (Official Video) Mohit Ladhotiya  Fiza Choudhary  New Haryanvi Song 2026  Nav Haryanvi.mp3",
  "Chambal K Dakku  Masoom Sharma  Swara Verma  Rahul Muana  Ruba Khan  New Haryanvi Song 2025.mp3",
  "Chhori Jail Karawegi Re.mp3",
  "Chole Bhature छल भटर  Diler Kharkiya  Anjali Raghav  New Haryanvi Song 2025  Moto Figure.mp3",
  "Dug Dug (Official Video) Aman Jaji, Fiza Choudhary  Raj Mawar, Ashu T  New Haryanvi DJ Song 2024.mp3",
  "Fortuner (Official Video) Gulshan Music,Jaat Nia,Ruchika Jangid  New Haryanvi Songs Haryanavi 2025.mp3",
  "Gold 18 Lakh Ka - Dholi Honda City Song  Yaar Lera Gadi 3 Pone 2 Crore Ki  Dhai Lakh Ka Suit Song.mp3",
  "Gypsy (Official Video) - Balam Thanedar  Pranjal Dahiya  Dinesh Golan  GD Kaur  Real Music.mp3",
  "Haryanvi Songs  Ishq  Haryanavi DJ Songs 2017  Mandeep Rana, Anjali Raghav  VOHM.mp3",
  "Hero Handa ( Official Music Video) Khushi Baliyan  Punit Choudhary  Raj Mawer  Latest Haryanvi Song.mp3",
  "Jale  Sapna Choudhary Dance Performance  New Haryanvi Songs Haryanavi 2023.mp3",
  "Jale 3  Sapna Choudhary Dance Performance  Goa  New Haryanvi song 2026.mp3",
  "Jalebi Juda   Haryanvi DJ Song 2017  Rakesh Tanwar  Anjali Raghav  Monika Sharma  VOHM.mp3",
  "KHASA AALA CHAHAR _ LOOT LIYA (Lyrical) New Haryanvi Songs Haryanavi 2021  Yaar Tera Full Papi Hai.mp3",
  "Kabootar - Renuka Panwar, Pranjal Dahiya, Vivek, Surender Romio, Aman Jaji, Rakesh Majreya, Sahil S.mp3",
  "Kale Kagaz (Lyrical Video) Amanraj Gill ft. Pranjal Dahiya  Shiva Choudhary  New Haryanvi Song.mp3",
  "Kue Upar - Komal Chaudhary Sunil Sikander  Ak Changia  Bharti Chaudhary  New haryanvi Song 2025.mp3",
  "Lapete  Sapna Choudhary Dance Video 2022  New Haryanvi Songs Haryanavi 2022.mp3",
  "Latest 2016 Moka Soka  Ajay Hooda  New Song  Raju & Anu Kadyan  Mor Music.mp3",
  "License Ka Asla - Licence  Masoom Sharma  Amar Karnawal.mp3",
  "MITHE TERE BOL PARI _ Masoom Sharma  Pranjal Dahiya  Aman Jaji  Mukesh  New Haryanvi Song 2026.mp3",
  "Madam Ji (Official Video) Masoom Sharma  Amar Karnawal, Pinna Music  New Haryanvi Song 2025.mp3",
  "Matak Chalungi - Sapna Choudhary, Aman Jaji, Raj Mawar, Manisha Sharma, Mukesh Jaji, Gulshan M, Ajay.mp3",
  "Mithi Boli  Anjali Raghav  Raju Punjabi  TONNY TANKRI  Durge Movies Haryanvi.mp3",
  "Mor Music  Laad Piya Ke  Pardeep Boora & Sapna  Raju Punjabi & Sushila  New Song 2016.mp3",
  "My Queen  Official Video   KD DESIROCK  Swara Verma  Muskan Verma  New Haryanvi Song 2024.mp3",
  "Naam Chale (Official Video) Vikram Sarkar  New Haryanvi Songs Haryanavi 2025 Latest Haryanvi Songs.mp3",
  "Nazra Ke Teer (Official Video) Vikram Sarkar New Haryanvi Songs Haryanavi 2024Latest Haryanvi Song.mp3",
  "New Haryanvi Songs Haryanvi 2021  Gajban Pani Ne Challi  Vishvjeet Chaudhary Ft. Sapna Choudhary.mp3",
  "No Snitching (Visualizer) Vin WRLD ft. Harshit Rao  prod by lunar  Aniket jain.mp3",
  "Olha Mein Patola.mp3",
  "Pani Chhalke (Official Video)  Sapna Choudhary  Manisha Sharma  New Haryanvi Songs Haryanavi 2022.mp3",
  "RUCHIKA JANGID  Patola (Official song) Gori Nagori  New Haryanvi Song Haryanvi 2022.mp3",
  "Ram Ram.mp3",
  "Rupinder Handa_ PIND DE GERHE (Full Song)  Desi Crew  New Punjabi Video 2015.mp3",
  "SAPNA CHOUDHARY _ Ghungroo Toot Jayega (Full Video)  UK Haryanvi  Haryanvi Songs Haryanavi 2021.mp3",
  "SOLID BODY  Ajay Hooda & Anjali Raghav  Raju Punjabi & Sheenam  New song of 2015  Mor Music.mp3",
  "Saadi Bholi (Official Video) Amanraj Gill  Pranjal Dahiya  New Haryanvi Songs 2026  Nav Haryanvi.mp3",
  "Sapna Dance _- Yaar Tera Chetak Pe Chale I Sapna Chaudhary I Sapna Live Performance 2022 I Sonotek.mp3",
  "System Pe System  R Maan  Billa Sonipat Aala  New Haryanvi Songs  Ek Mere Bol Pa System Hilega.mp3",
  "Tag Awara Ke (Official Video) Amanraj Gill, Shivani Yadav, Shiva Choudhary  New Haryanvi Song 2024.mp3",
  "Teri Aakhya Ka Yo Kajal  Superhit Sapna Song  New Haryanvi Video Song 2018.mp3",
  "Teri Kothi Mein Banwadu.mp3",
  "Thada Bhartar  ( Lyrical Video ) Sapna Choudhary  Raju Punjabi  New Haryanvi Songs Haryanvi 2026.mp3",
  "Tu Cheej Lajwaab  त चज लजबब  Pardeep Boora & Sapna Chaudhary  New Haryanvi Song.mp3",
  "ओलह म पटल Olha Song हय हय मरजण Ajay Hooda  Masoom Sharma  Pooja Hooda  Haryanvi DJ Song.mp3",
  "तगड # Tagdi # Ajay Hooda # New DJ Song 2018 # Gagan & Anu Kadyan # Mor Music.mp3",
  "तर लत लग जग I Teri Lat Lag jagi Sapna Chaudhary I Hit Song I Sapna Live ShowSapna Entertaiment.mp3",
  "बनदक चलक सपन चधर न कय घमसन डस  भड़ हई बकब  Haryanvi New Video  Trimurti.mp3",
  "सपन चधर क आ गय नय गन , 2024 Ka Sabse Bada Hit Song  Chetak 2 Song 2024  Sonotek Ragni.mp3"
];
