window.trackFiles = [
  "#ANKUSH RAJA  Aso Chhath Karab Naihar Mein - अस छठ करब नईहर म  #Shilpi Raj  Chhath Geet Song.mp3",
  "#Ankush Raja क सबस सपरहट छठ गत 2021 - Chhathi Mai Ke Mahima - Bhojpuri Chhath Geet 2021.mp3",
  "#AnuDubey क य छठ गत महलय क बच बहत ह पसद कय ज रह ह  #Chhath #Geet 2023.mp3",
  "#Kalpana क सबस हट #Chhath Song - Ugi Hey Dinanath  Superhit Chhath Geet 2023.mp3",
  "#Khesari Lal Yadav  #Video - छठ पज न कईल त क कईल  Ft - Yamini Singh  Bhojpuri Chhath Geet.mp3",
  "#Khesari Lal Yadav क सबस बड़ छठ सग Kaise Chhath Karab Ho कस छठ करब ह.mp3",
  "#Khesari Lal Yadav हट छठ गत #Chhathi Maiya Ghare Ghar Jali छठ मईय घर घर जल.mp3",
  "#Pawan Singh क सपरहट छठ गत  पनहल महदव पयरय  Bhojpuri Chath Song 2022 (1).mp3",
  "#Pawan Singh क सपरहट छठ गत  पनहल महदव पयरय  Bhojpuri Chath Song 2022.mp3",
  "#Pawan Singh क सबस बड़ हट छठ गत - Deke Darshan Bhale Chal Jayi Ji - Bhojpuri Chhath Geet.mp3",
  "#Pawan Singh क सबस मठ छठ गत  कस जइब छठ घट  Bhojpuri Chath Song 2021.mp3",
  "#RiteshPandey क सबस HIT #छठगत 2018 - Paawan Parav Chhathi Mai Ke - Bhojpuri Chhath Geet.mp3",
  "#Video  #Ankush Raja, #Kajal Raghwani क छठ गत  बट द दS य मई  Bhojpuri New Chhath Geet 2022.mp3",
  "#video  #Khesari Lal New Song  नरयल  #Shilpi Raj  Nariyal  #Bhojpuri Song  Chhat Geet.mp3",
  "#Video  #Khesari Lal Yadav  छठ मईय  #Antra Singh  Chhathi Maiya  New Chhath Song 2021.mp3",
  "#Video  #Pawan Singh  कवन कलमव स लखलऽ करमव  #Priyanka Singh  Bhojpuri Chhath Geet 2025.mp3",
  "#Video  अरघ क बर  #Khesari Lal Yadav  Aragh ke Bera  #Shilpi Raj  Bhojpuri Chhath Song 2024.mp3",
  "#Video  चचहय बल लगल  #Khesari Lal Yadav  Chuchuhiya Bole Lagal  Chhath Geet 2014.mp3",
  "#VIDEO  छठ घट चल  #Khesari Lal Yadav , #Antra Singh Priyanka  Bhojpuri Chhath Puja Song.mp3",
  "#Video  छड़छड़ ए भऊज  #Khesari Lal Yadav क हट छठ गत  Chhudchhudi A Bhauji  New Chhath Geet.mp3",
  "#VIDEO  पयव चलवल टरक छठ मईय  #Gunjan Singh, #Shilpi Raj  Maghi Chhath Geet 2021.mp3",
  "#VIDEO  पर खतर पयर पय  #Khesari Lal Yadav, Neelam Giri, #Shilpi Raj  Chhath Puja Song 2024.mp3",
  "#Video  मथव प लक दउरव  #Neelkamal Singh  #छठ गत  Bhojpuri Chhath Song 2022.mp3",
  "#VIDEO  लरव स भज अचरव  #Pawan Singh, #Palak Muchhal  Lorawa Se Bhije Acharwa  Chhath Song.mp3",
  "#VIDEO  सवगतम छठ मईय क #Pawan Singh Swagatam Chhthi Maiya Ke Bhojpuri Chhath Puja Song 2021.mp3",
  "#Video #Pawan Singh  कश कईल घर उजड  Kosi Kaili Ghar Ujad  #भजपर Chhath Geet 2025.mp3",
  "#Video - #परमपरक #छठ गत - ओर तर - #Ankush Raja - Ori Tar - Bhojpuri Paramparik Chhath Song 2025.mp3",
  "#Video - Hokhi Sahaiya Hey Chhathi Maiya  #Pawan Singh  Khushboo Jain  Bhojpuri Chhath Geet 2022.mp3",
  "#Video - कच ह बस क बहगय  #Khesari Lal yadav ( परमपरक छठ गत ) #Kalpana  Chhath Geet.mp3",
  "#Video - कशय भरय लगल - #Neelkamal Singh - #Priyanka Singh - Bhojpuri New Chhath Geet 2023.mp3",
  "#Video - पटन क घट  #Pawan Singh  Patna Ke Ghat  Ft, Pooja Nishad  Bhojpuri Chhath Geet 2023.mp3",
  "#Video - पयर पहर लऽ  #Pawan Singh, #Shivani Singh  Piyari Pahir La  Bhojpuri Chhath Geet 2023.mp3",
  "#Video - परमपरक छठ गत - दरशन दखई दह- #Kalpana Patawory - #Ritu  -Bhojpuri Chhath Geet 2023.mp3",
  "#VIDEO घट भर मर धत भज  #Khesari Lal Yadav  Ghutti Bhar Mor Dhoti Bhije  Chhath Song 2021.mp3",
  "#Video-ककर घर क फलव  #Aashish Yadav क मगह छठ गन  Kekar Ghar Ke Phulwa  #Chhath Geet 2023.mp3",
  "#अकषर सह  जड़ जड़ फलव  #Akshara Singh  Jode Jode Phalwa  Bhojpuri Chhath Song.mp3",
  "Aadit Manaila Bhojpuri Chhath Geet [Full Video] I Chhath Pooja Ke Geet.mp3",
  "Bhukhal Piyasal Ghatiya आईल बन  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet.mp3",
  "Chala Patana Ke Ghat  चलs पटन क घट  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet 2025.mp3",
  "Chath Karab hum jaroor(छठ करब हम जरर)  Swati Mishra  Chath Song 2024.mp3",
  "Chatpujasongcollection2022....#trending#new#chatpuja#chatpuja2022#song#festival.mp3",
  "Chhathi Maiya Bulaye - Vishal Mishra  Kaushal Kishore  Desh Unplugged  Chhath Song 2021.mp3",
  "Chhor ke  aai arab  CHHATHI GHATE CHALI  KHESHARI LAL.mp3",
  "Daoora Uthava Na Bihari Babu [Full Song] Mahima Chhath Maiyya Ke Apaar.mp3",
  "Dhaniya Hamar Naya Baadi Ho  #pawansingh #neelamgiri  धनय हमर नय बड़ ह    #chhath  गत.mp3",
  "Full Video  आह आदतमल  #Karina Pandey  #Sovita Pandey  Aahe Aaditmal  Chhath Special Song 2025 (1).mp3",
  "Full Video  आह आदतमल  #Karina Pandey  #Sovita Pandey  Aahe Aaditmal  Chhath Special Song 2025.mp3",
  "Gunjan Singh क सबस हट छठ गत - VIDEO SONG 2020  बनब नद कनर घट र  Maghi Chhath Geet 2020.mp3",
  "HD  ह छठ मई तहक गहरई - Lachkela Bahangi - Pawan Singh - Bhojpuri Hit Songs 2015.mp3",
  "HD VIDEO #  पटन क घट नक लगल  Khesari Lal Yadav , Dimpal Chandani  Bhojpuri Chhath Geet 2017.mp3",
  "HD कन ल आइह बस क सपलय - Chhath Puja Kar Li - Khesari Lal -  Bhojpuri Chhath Geet.mp3",
  "HD छठ मई हइह सहय - Mathe Daura Uthai Ke - Pawan Singh - Bhojpuri Chhath Songs 2015 new.mp3",
  "HD बदर चर क आई उग ह सरयदव - Mathe Daura Uthai Ke - Pawan Singh - Bhojpuri Chhath Songs 2025.mp3",
  "HD लचकल बहग झमल बहरय - Lachkela Bahangi - Pawan Singh - Bhojpuri Hit Songs.mp3",
  "Hey Chhathi Maiya Sharda Sinha Bhojpuri Chhath Songs [Full HD Song] I Chhathi Maiya.mp3",
  "Ho Deenanath By Sharda Sinha Bhojpuri Chhath Pooja Geet [Full HD Song] I CHHATHI MAIYA.mp3",
  "Jai Chhathi Maiya  Sonu Nigam, Pawan Singh & Khushboo Jain  Harshika Poonacha  Chhath Geet 2021.mp3",
  "Kekra Khatir Naa - Chath geet - Arvind Akela Kallu Ji - Chhathi maiya bhajan.mp3",
  "KELWA KE PAAT PAR Bhojpuri Chhath Pooja Geet DEVI I Full HD Video Song I BAHANGI CHHATH MAAI KE JAAY.mp3",
  "Khesari Lal Yadav & Kajal Raghwani छपर म छठ मनएग Chhapra Chhat Manayenge - Stage Show.mp3",
  "Khesari Lal Yadav क छठ गत VIDEO  Chhath Kare Jaib Naihar Mein  Chhath Song  Ishtar Bhojpuri.mp3",
  "Khesari Lal Yadav क सबस हट छठ गत VIDEO  Patna Ke Ghat Nik Lagela  Bhojpuri Chhath Song.mp3",
  "Khesari Lal Yadav छठ पज Song #HD VIDEO  Na Sajanwa Aile Ho  Bhojpuri Chhath Puja Geet.mp3",
  "Khesari Lal Yadav पहल छठ गत  Chala Ganga Kinare -Karishma Kakkar  Bhojpuri Chhath Puja Song 2023 (1).mp3",
  "Khesari Lal Yadav पहल छठ गत  Chala Ganga Kinare -Karishma Kakkar  Bhojpuri Chhath Puja Song 2023.mp3",
  "KOPI KOPI BOLELI Bhojpuri Chhath Pooja Geet DEVI I Full HD Video Song I BAHANGI CHHATH MAAI KE JAAY.mp3",
  "Lyrical  कहल महदव कर हथ जड़य  Pawan Singh  Kahele Mahadev  Bhojpuri Chhath Geet 2024.mp3",
  "Maath Pa Daurawa Leke #riteshpandey   मथ पS दउरव लक  #chhath #chhathsong.mp3",
  "Marabo Re Sugawa Dhanush Se  #Kalpana Patowary  Chhath Geet  Cover Chhath Song.mp3",
  "Nagin करल छठ मई क वरत - Nagin - Bhojpuri Movie Chhath Songs - Chhathi Mayi Ke Karab Baratiyaa.mp3",
  "Pahile Pahil Chhathi Maiya  #Sharda Sinha  Chhath Song.mp3",
  "Pawan Singh - छठ मई क घटव प आजन बजन - Chhathi Mai Ke Mahima Apar - Bhojpuri Chhath Geet.mp3",
  "Pawan Singh क Superhit Chhath Geet 2019  छठ मईय क हत आगमन  Chhathi Maiya Ke Hota Aagman.mp3",
  "Pawan Singh क Superhit Chhath Geet Video Song 2019  Chhathi Maiya Ke Hota Aagman.mp3",
  "Pawan Singh क सबस सदर छठ गत - आदतमल हइह सहईय, त छठ कर भईय - Paramparik Chhath Geet.mp3",
  "Rauwa Se Ehe हथजरय न ह  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet 2025.mp3",
  "Sama Khele Chalali By Sharda Sinha Bhojpuri Chhath Songs [Full Song] Chhathi Maiya.mp3",
  "SANGHE JAAYEM AE BALAM JI Bhojpuri Chhath Songs [Full HD Song] SURAJ KE RATH.mp3",
  "song.mp3",
  "Special Ta Uga Hai Suraj Dev  Anuradha Paudwal  Hindi-English Lyrics  Chhath Puja.mp3",
  "Ugi He Dinanath  उग ह दननथ  Ugi Hey Dinanath  Kalpna  Bhojpuri Chhath Geet 2025.mp3",
  "Video  #छठगत  #Neelkamal Singh  कशय भरय लगल  #Priyanka Singh  Bhojpuri Chhath Geet 2023.mp3",
  "Video - Ugi Hey Dinanath  Swati Mishra  New Chhath Geet  Chhath Pooja Special Song 2024.mp3",
  "आर आर सईय - Chamkela Ghat Chhathi Mai Ke - Golu Gold - Bhojpuri Chhath Geet.mp3",
  "उग ह सरयमल नइय  न डल - Pawan Singh - Chhathi Mai Ke Mahima Apar - Bhojpuri Chhath Geet.mp3",
  "उग ह सरयमल नइय न डल - #Pawan Singh Chhath Song - #Bhojpuri Superhit Chhath Geet.mp3",
  "कच ह बस क बहगय - Aragh Dehab Suraj Dev Ke  Arvind Akela Kalluji  Chhath Pooja Song 2025.mp3",
  "कदआ भत ग रनय   छठ गत वडय 2020  Gunjan Singh & Antra Singh Priyanka  Chhath Puja Song.mp3",
  "कर मई कठन बरतय  Lyrics -Swati Mishra Official Chath Song.mp3",
  "करव क पतव प नवत  #Pawan Singh  Kerawa Ke Patawa Pa Newta Pethawani  Lyrical Chhath Geet.mp3",
  "करव क पतव प नवत  #Pawan Singh क धकड़ छठ गत 2022  Superhit Bhojpuri Chhath Geet 2022.mp3",
  "कलपन क परमपरक छठ गत 2018  भईल अरघय क बर  New Bhojpuri Chhath Geet -#Sanjivani(SM).mp3",
  "खसर लल क महपरव छठ पज क सबस हट गत - चहमख दय जल Chaumukhi Diya Jale  Daura Sajali.mp3",
  "घर घर हत Chhathi Maai क Varatiya  Aamrapali Dubey  भजपर Chhath गत  Song 2019.mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song (1).mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song (2).mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song.mp3",
  "छठ पज I छठ क बरतय I Chhath Ke Baratiya I Sharda Sinha  Aditya Dev I Vishal Singh IAnand Mishra.mp3",
  "छठ मई क घटव प आजन बजन  Pawan Singh  Chhathi Mai Ke Mahima Apar  Bhojpuri Chhath Geet.mp3",
  "झमक गरल ब छठ घट प  Jhumka Giral Ba Chhathi Ghat Pe  Khesari Lal Yadav  Chaithi Chhat  Song.mp3",
  "नरयलव अरघ चढ़ Nariyalwa Aragh Chadhe Ho Chhath Pooja GeetKALPANA,Chhathi Maiya Aaihein Hamaar.mp3",
  "पवन सह क सबस जयद बजन वल छठ गत - जड़ जड़ फलव T-Series #chhathpuja Jode Jode Falwa.mp3",
  "बदय बन दs छठ घट - Chhath Puja Kar Li - Khesari Lal -  Bhojpuri Chhath Geet @WaveMusicIndia.mp3",
  "मकअप क फर अरघ क बर Makeup Ke Phera Aragh Ke Bera  Khesari Lal Yadav  Priyanka Singh Chhath.mp3",
  "रजन सघ क हट छठ गत- उग ह सरज दव न -2017 Ranjana Singh Chhat Geet - New Hit Chhath Geet.mp3",
  "लचकल बहग झमल बहरय - Lachkela Bahangi - Pawan Singh - Bhojpuri Chhath Geet 2016.mp3"
];
