window.trackFiles = [
  "#ANKUSH RAJA  Aso Chhath Karab Naihar Mein - अस छठ करब नईहर म  #Shilpi Raj  Chhath Geet Song.mp3",
  "#Ankush Raja क सबस सपरहट छठ गत 2021 - Chhathi Mai Ke Mahima - Bhojpuri Chhath Geet 2021.mp3",
  "#AnuDubey क य छठ गत महलय क बच बहत ह पसद कय ज रह ह  #Chhath #Geet 2023.mp3",
  "#Kalpana क सबस हट #Chhath Song - Ugi Hey Dinanath  Superhit Chhath Geet 2023.mp3",
  "#Khesari Lal Yadav  #Video - छठ पज न कईल त क कईल  Ft - Yamini Singh  Bhojpuri Chhath Geet.mp3",
  "#Khesari Lal Yadav क सबस बड़ छठ सग Kaise Chhath Karab Ho कस छठ करब ह.mp3",
  "#Khesari Lal Yadav हट छठ गत #Chhathi Maiya Ghare Ghar Jali छठ मईय घर घर जल.mp3",
  "#Pawan Singh क सपरहट छठ गत  पनहल महदव पयरय  Bhojpuri Chath Song 2022 (1).mp3",
  "#Pawan Singh क सपरहट छठ गत  पनहल महदव पयरय  Bhojpuri Chath Song 2022.mp3",
  "#Pawan Singh क सबस बड़ हट छठ गत - Deke Darshan Bhale Chal Jayi Ji - Bhojpuri Chhath Geet.mp3",
  "#Pawan Singh क सबस मठ छठ गत  कस जइब छठ घट  Bhojpuri Chath Song 2021.mp3",
  "#RiteshPandey क सबस HIT #छठगत 2018 - Paawan Parav Chhathi Mai Ke - Bhojpuri Chhath Geet.mp3",
  "#Video  #Ankush Raja, #Kajal Raghwani क छठ गत  बट द दS य मई  Bhojpuri New Chhath Geet 2022.mp3",
  "#video  #Khesari Lal New Song  नरयल  #Shilpi Raj  Nariyal  #Bhojpuri Song  Chhat Geet.mp3",
  "#Video  #Khesari Lal Yadav  छठ मईय  #Antra Singh  Chhathi Maiya  New Chhath Song 2021.mp3",
  "#Video  #Pawan Singh  कवन कलमव स लखलऽ करमव  #Priyanka Singh  Bhojpuri Chhath Geet 2025.mp3",
  "#Video  अरघ क बर  #Khesari Lal Yadav  Aragh ke Bera  #Shilpi Raj  Bhojpuri Chhath Song 2024.mp3",
  "#Video  चचहय बल लगल  #Khesari Lal Yadav  Chuchuhiya Bole Lagal  Chhath Geet 2014.mp3",
  "#VIDEO  छठ घट चल  #Khesari Lal Yadav , #Antra Singh Priyanka  Bhojpuri Chhath Puja Song.mp3",
  "#Video  छड़छड़ ए भऊज  #Khesari Lal Yadav क हट छठ गत  Chhudchhudi A Bhauji  New Chhath Geet.mp3",
  "#VIDEO  पयव चलवल टरक छठ मईय  #Gunjan Singh, #Shilpi Raj  Maghi Chhath Geet 2021.mp3",
  "#VIDEO  पर खतर पयर पय  #Khesari Lal Yadav, Neelam Giri, #Shilpi Raj  Chhath Puja Song 2024.mp3",
  "#Video  मथव प लक दउरव  #Neelkamal Singh  #छठ गत  Bhojpuri Chhath Song 2022.mp3",
  "#VIDEO  लरव स भज अचरव  #Pawan Singh, #Palak Muchhal  Lorawa Se Bhije Acharwa  Chhath Song.mp3",
  "#VIDEO  सवगतम छठ मईय क #Pawan Singh Swagatam Chhthi Maiya Ke Bhojpuri Chhath Puja Song 2021.mp3",
  "#Video #Pawan Singh  कश कईल घर उजड  Kosi Kaili Ghar Ujad  #भजपर Chhath Geet 2025.mp3",
  "#Video - #परमपरक #छठ गत - ओर तर - #Ankush Raja - Ori Tar - Bhojpuri Paramparik Chhath Song 2025.mp3",
  "#Video - Hokhi Sahaiya Hey Chhathi Maiya  #Pawan Singh  Khushboo Jain  Bhojpuri Chhath Geet 2022.mp3",
  "#Video - कच ह बस क बहगय  #Khesari Lal yadav ( परमपरक छठ गत ) #Kalpana  Chhath Geet.mp3",
  "#Video - कशय भरय लगल - #Neelkamal Singh - #Priyanka Singh - Bhojpuri New Chhath Geet 2023.mp3",
  "#Video - पटन क घट  #Pawan Singh  Patna Ke Ghat  Ft, Pooja Nishad  Bhojpuri Chhath Geet 2023.mp3",
  "#Video - पयर पहर लऽ  #Pawan Singh, #Shivani Singh  Piyari Pahir La  Bhojpuri Chhath Geet 2023.mp3",
  "#Video - परमपरक छठ गत - दरशन दखई दह- #Kalpana Patawory - #Ritu  -Bhojpuri Chhath Geet 2023.mp3",
  "#VIDEO घट भर मर धत भज  #Khesari Lal Yadav  Ghutti Bhar Mor Dhoti Bhije  Chhath Song 2021.mp3",
  "#Video-ककर घर क फलव  #Aashish Yadav क मगह छठ गन  Kekar Ghar Ke Phulwa  #Chhath Geet 2023.mp3",
  "#अकषर सह  जड़ जड़ फलव  #Akshara Singh  Jode Jode Phalwa  Bhojpuri Chhath Song.mp3",
  "Aadit Manaila Bhojpuri Chhath Geet [Full Video] I Chhath Pooja Ke Geet.mp3",
  "Bhukhal Piyasal Ghatiya आईल बन  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet.mp3",
  "Chala Patana Ke Ghat  चलs पटन क घट  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet 2025.mp3",
  "Chath Karab hum jaroor(छठ करब हम जरर)  Swati Mishra  Chath Song 2024.mp3",
  "Chatpujasongcollection2022....#trending#new#chatpuja#chatpuja2022#song#festival.mp3",
  "Chhathi Maiya Bulaye - Vishal Mishra  Kaushal Kishore  Desh Unplugged  Chhath Song 2021.mp3",
  "Chhor ke  aai arab  CHHATHI GHATE CHALI  KHESHARI LAL.mp3",
  "Daoora Uthava Na Bihari Babu [Full Song] Mahima Chhath Maiyya Ke Apaar.mp3",
  "Dhaniya Hamar Naya Baadi Ho  #pawansingh #neelamgiri  धनय हमर नय बड़ ह    #chhath  गत.mp3",
  "Full Video  आह आदतमल  #Karina Pandey  #Sovita Pandey  Aahe Aaditmal  Chhath Special Song 2025 (1).mp3",
  "Full Video  आह आदतमल  #Karina Pandey  #Sovita Pandey  Aahe Aaditmal  Chhath Special Song 2025.mp3",
  "Gunjan Singh क सबस हट छठ गत - VIDEO SONG 2020  बनब नद कनर घट र  Maghi Chhath Geet 2020.mp3",
  "HD  ह छठ मई तहक गहरई - Lachkela Bahangi - Pawan Singh - Bhojpuri Hit Songs 2015.mp3",
  "HD VIDEO #  पटन क घट नक लगल  Khesari Lal Yadav , Dimpal Chandani  Bhojpuri Chhath Geet 2017.mp3",
  "HD कन ल आइह बस क सपलय - Chhath Puja Kar Li - Khesari Lal -  Bhojpuri Chhath Geet.mp3",
  "HD छठ मई हइह सहय - Mathe Daura Uthai Ke - Pawan Singh - Bhojpuri Chhath Songs 2015 new.mp3",
  "HD बदर चर क आई उग ह सरयदव - Mathe Daura Uthai Ke - Pawan Singh - Bhojpuri Chhath Songs 2025.mp3",
  "HD लचकल बहग झमल बहरय - Lachkela Bahangi - Pawan Singh - Bhojpuri Hit Songs.mp3",
  "Hey Chhathi Maiya Sharda Sinha Bhojpuri Chhath Songs [Full HD Song] I Chhathi Maiya.mp3",
  "Ho Deenanath By Sharda Sinha Bhojpuri Chhath Pooja Geet [Full HD Song] I CHHATHI MAIYA.mp3",
  "Jai Chhathi Maiya  Sonu Nigam, Pawan Singh & Khushboo Jain  Harshika Poonacha  Chhath Geet 2021.mp3",
  "Kekra Khatir Naa - Chath geet - Arvind Akela Kallu Ji - Chhathi maiya bhajan.mp3",
  "KELWA KE PAAT PAR Bhojpuri Chhath Pooja Geet DEVI I Full HD Video Song I BAHANGI CHHATH MAAI KE JAAY.mp3",
  "Khesari Lal Yadav & Kajal Raghwani छपर म छठ मनएग Chhapra Chhat Manayenge - Stage Show.mp3",
  "Khesari Lal Yadav क छठ गत VIDEO  Chhath Kare Jaib Naihar Mein  Chhath Song  Ishtar Bhojpuri.mp3",
  "Khesari Lal Yadav क सबस हट छठ गत VIDEO  Patna Ke Ghat Nik Lagela  Bhojpuri Chhath Song.mp3",
  "Khesari Lal Yadav छठ पज Song #HD VIDEO  Na Sajanwa Aile Ho  Bhojpuri Chhath Puja Geet.mp3",
  "Khesari Lal Yadav पहल छठ गत  Chala Ganga Kinare -Karishma Kakkar  Bhojpuri Chhath Puja Song 2023 (1).mp3",
  "Khesari Lal Yadav पहल छठ गत  Chala Ganga Kinare -Karishma Kakkar  Bhojpuri Chhath Puja Song 2023.mp3",
  "KOPI KOPI BOLELI Bhojpuri Chhath Pooja Geet DEVI I Full HD Video Song I BAHANGI CHHATH MAAI KE JAAY.mp3",
  "Lyrical  कहल महदव कर हथ जड़य  Pawan Singh  Kahele Mahadev  Bhojpuri Chhath Geet 2024.mp3",
  "Maath Pa Daurawa Leke #riteshpandey   मथ पS दउरव लक  #chhath #chhathsong.mp3",
  "Marabo Re Sugawa Dhanush Se  #Kalpana Patowary  Chhath Geet  Cover Chhath Song.mp3",
  "Nagin करल छठ मई क वरत - Nagin - Bhojpuri Movie Chhath Songs - Chhathi Mayi Ke Karab Baratiyaa.mp3",
  "Pahile Pahil Chhathi Maiya  #Sharda Sinha  Chhath Song.mp3",
  "Pawan Singh - छठ मई क घटव प आजन बजन - Chhathi Mai Ke Mahima Apar - Bhojpuri Chhath Geet.mp3",
  "Pawan Singh क Superhit Chhath Geet 2019  छठ मईय क हत आगमन  Chhathi Maiya Ke Hota Aagman.mp3",
  "Pawan Singh क Superhit Chhath Geet Video Song 2019  Chhathi Maiya Ke Hota Aagman.mp3",
  "Pawan Singh क सबस सदर छठ गत - आदतमल हइह सहईय, त छठ कर भईय - Paramparik Chhath Geet.mp3",
  "Rauwa Se Ehe हथजरय न ह  Mahima Chhathi Maiya Ke  Pawan Singh  Chhath Geet 2025.mp3",
  "Sama Khele Chalali By Sharda Sinha Bhojpuri Chhath Songs [Full Song] Chhathi Maiya.mp3",
  "SANGHE JAAYEM AE BALAM JI Bhojpuri Chhath Songs [Full HD Song] SURAJ KE RATH.mp3",
  "song.mp3",
  "Special Ta Uga Hai Suraj Dev  Anuradha Paudwal  Hindi-English Lyrics  Chhath Puja.mp3",
  "Ugi He Dinanath  उग ह दननथ  Ugi Hey Dinanath  Kalpna  Bhojpuri Chhath Geet 2025.mp3",
  "Video  #छठगत  #Neelkamal Singh  कशय भरय लगल  #Priyanka Singh  Bhojpuri Chhath Geet 2023.mp3",
  "Video - Ugi Hey Dinanath  Swati Mishra  New Chhath Geet  Chhath Pooja Special Song 2024.mp3",
  "आर आर सईय - Chamkela Ghat Chhathi Mai Ke - Golu Gold - Bhojpuri Chhath Geet.mp3",
  "उग ह सरयमल नइय  न डल - Pawan Singh - Chhathi Mai Ke Mahima Apar - Bhojpuri Chhath Geet.mp3",
  "उग ह सरयमल नइय न डल - #Pawan Singh Chhath Song - #Bhojpuri Superhit Chhath Geet.mp3",
  "कच ह बस क बहगय - Aragh Dehab Suraj Dev Ke  Arvind Akela Kalluji  Chhath Pooja Song 2025.mp3",
  "कदआ भत ग रनय   छठ गत वडय 2020  Gunjan Singh & Antra Singh Priyanka  Chhath Puja Song.mp3",
  "कर मई कठन बरतय  Lyrics -Swati Mishra Official Chath Song.mp3",
  "करव क पतव प नवत  #Pawan Singh  Kerawa Ke Patawa Pa Newta Pethawani  Lyrical Chhath Geet.mp3",
  "करव क पतव प नवत  #Pawan Singh क धकड़ छठ गत 2022  Superhit Bhojpuri Chhath Geet 2022.mp3",
  "कलपन क परमपरक छठ गत 2018  भईल अरघय क बर  New Bhojpuri Chhath Geet -#Sanjivani(SM).mp3",
  "खसर लल क महपरव छठ पज क सबस हट गत - चहमख दय जल Chaumukhi Diya Jale  Daura Sajali.mp3",
  "घर घर हत Chhathi Maai क Varatiya  Aamrapali Dubey  भजपर Chhath गत  Song 2019.mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song (1).mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song (2).mp3",
  "चह नह अन धन खजनव - Bahangi Chhathi Mai Ke  Arvind Akela Kalluji, Nisha Ji  Chhath Pooja Song.mp3",
  "छठ पज I छठ क बरतय I Chhath Ke Baratiya I Sharda Sinha  Aditya Dev I Vishal Singh IAnand Mishra.mp3",
  "छठ मई क घटव प आजन बजन  Pawan Singh  Chhathi Mai Ke Mahima Apar  Bhojpuri Chhath Geet.mp3",
  "झमक गरल ब छठ घट प  Jhumka Giral Ba Chhathi Ghat Pe  Khesari Lal Yadav  Chaithi Chhat  Song.mp3",
  "नरयलव अरघ चढ़ Nariyalwa Aragh Chadhe Ho Chhath Pooja GeetKALPANA,Chhathi Maiya Aaihein Hamaar.mp3",
  "पवन सह क सबस जयद बजन वल छठ गत - जड़ जड़ फलव T-Series #chhathpuja Jode Jode Falwa.mp3",
  "बदय बन दs छठ घट - Chhath Puja Kar Li - Khesari Lal -  Bhojpuri Chhath Geet @WaveMusicIndia.mp3",
  "मकअप क फर अरघ क बर Makeup Ke Phera Aragh Ke Bera  Khesari Lal Yadav  Priyanka Singh Chhath.mp3",
  "रजन सघ क हट छठ गत- उग ह सरज दव न -2017 Ranjana Singh Chhat Geet - New Hit Chhath Geet.mp3",
  "लचकल बहग झमल बहरय - Lachkela Bahangi - Pawan Singh - Bhojpuri Chhath Geet 2016.mp3"
];

const bhojpuriTrackPattern = /bhojpuri|भोजपुरी|pawan singh|pawansingh|khesari|kheshari|ankush raja|ritesh pandey|kalpana|sharda sinha|gunjan singh|neelkamal|arvind akela|golu gold|antra singh|shilpi raj|anu ?dubey|aashish yadav|swati mishra|ranjana singh|chhath geet|chath song|chhath song|chhat geet|छठ गीत|छठ गत|छठ पज/i;
window.trackFiles = [...new Set(window.trackFiles)].sort((firstTrack, secondTrack) => {
  return Number(bhojpuriTrackPattern.test(firstTrack)) - Number(bhojpuriTrackPattern.test(secondTrack));
});

window.navratriTrackFiles = [...new Set([
  "Aa Maa Aa Tujhe Dil Ne Pukara with Hindi, English Lyrics I Mamta Ka Mandir I Lyrical Video.mp3",
  "Ambe Tu Hai Jagdambe Kaali  Narendra Chanchal  Ambe Maa Aarti  Mata Aarti  Ambe Maa Bhajan.mp3",
  "Angana padharo maharani Original  अगन पधर महरन ओरजनल- मनष मन.mp3",
  "Bhor Bhai Din Chad Gaya Meri Ambe - Ambe Maa Aarti  Mata Ki Aarti  Mata Ke Bhajan  Alka Yagnik.mp3",
  "Bigdi Meri Bana De Devi Bhajan By Lakhbir Singh Lakkha [Full Song] Beta Bulaye.mp3",
  "CHHUM CHHUM CHANANANA BAAJE - छम छम छननन बज - Shahnaz Akhatar - Audio Song - Durga Mata Song.mp3",
  "Durga Hai Meri Maa Lyrical  दरग ह मर म  Mahendra Kapoor  Minoo P  Laxmikant-Pyarelal.mp3",
  "Jode Chunri - Jode Kalsha.mp3",
  "Jubin Nautiyal_ Meri Maa Ke Barabar Koi Nahi  Payal Dev  Manoj Muntashir  Lovesh N Bhushan Kumar.mp3",
  "LAKHBIR SINGH LAKKHA Devi Bhajan, Ab Ke Navraatre Mere Angna Padharo,Maa Dar Pe Bulayegi,मत क भजन.mp3",
  "Lata Mangeshkar - Aaj Tera Jagraata.mp3",
  "Maa Main Khada Dwar Tere  Lakhbir Singh Lakkha Navratri Special Bhajan 2026 Sherawali Maa Bhajan.mp3",
  "Mai Sabse Badi Hai Tu.mp3",
  "Mere Naino Ki Pyas Bujha De  Devi Bhajan  SONU NIGAM  Jai Maa Vaishnav Devi  Full HD Video.mp3",
  "Meri Maa Ke Barabar Koi Nahi (Lyrical)  Jubin N & Payal D  Manoj Muntashir  Lovesh N  Bhushan K.mp3",
  "Navratri Special_SONU NIGAM Devi Bhajan,Sawan Ki Rut Hai Aaja Maa with Lyrics,सवन क रत ह आज म.mp3",
  "O Aaye Tere Bhawan with Hindi English  Lyrics I ANURADHA PAUDWAL,SONU NIGAM, Jai Maa Vaishno Devi.mp3",
  "PYARA SAJA HAI TERA DWAR [Full Song] -PYARA SAJA HAI TERA DWAR BHAWANI.mp3",
  "Shahnaaz Akhtar  Shankar Chaura Re  शकर चर र  Navratra Special Devi Bhajans.mp3",
  "Superhit Mata Ki Bhent I तझ कबस पकर तर लल I Tujhe Kab Se Pukare Tera Laal I SONU NIGAM I HD.mp3",
  "Tali Baja Lena  Bali Thakre  Riza Khan  Mata Ke Bhajan Song  Chhattisgarhi Devi Bhakti Geet.mp3",
  "Tune Mujhe Bulaya Sherawaliye  Navratri Special Song  Jai Mata Di  #navratri #trending #bhakti.mp3",
  "दनय स दर ज रह ह म तर पस आ रह ह 4K  Aarzoo  Akshay Kumar  Sonu Nigam, Anu Malik.mp3",
  "धरत गगन म हत ह Dharti Gagan Mein Hoti Hai, SURESH WADKAR,ANURADHA PAUDWAL,Hindi English Lyrics.mp3",
  "ननह ननह पव मर Nanhe Nanhe Paanv Mere I Hindi English Lyrics I SONU NIGAM, Full HD Video Song.mp3",
  "पयर सज ह तर दवर भवन I Pyara Saja Hai Tera Dwar Bhawani I LAKHBIR SINGH LAKKHA I Navratri.mp3",
  "बरश क छम छम म Barishon Ki Chham Chham Mein   UDIT NARAYAN  ANURADHA PAUDWAL  Jaikara.mp3",
  "लक पज क Leke Pooja Ki Thali,HD Video,SURESH WADKAR,Hindi English Lyrics,Jai Maa Vaishnodevi.mp3",
  "#Khesari lal Yadav क यह भजन सनकर तन बदन झम ऊठग - #KhesariLal Yadav - #Bhojpuri #Devi geet 2019.mp3",
  "#KhesariLalYadav क सपरहट दव गत - मईय अईल अगन - Bhojpuri Devi Geet 2018.mp3",
  "#Pawan Singh - मई ह तन आ जईत  #Bhakti Song  #Mai Ho Tani Aa Jaitu  Bhojpuri Hit Of Dussehra.mp3",
  "#Pawan Singh Navratri Song  मर मइय तह पयर क समदर ह  Meri Maiya Tuhi Pyar Ka Samandar Hai.mp3",
  "#Pawan Singh और #Priyanka Singh  Maai Ke Chunariya  Full Video  #Bhojpuri Devi Geet.mp3",
  "#Pawan Singh नवरतर क सबस हट सग - गग ज नहइब ए मईय - Ganga Ji Nahaibo Ye Maiya -Devi Geet.mp3",
  "#PawanSingh  मफ़ कर य मईय   #पवन सह  New Saraswati Puja Bhakti Song 2024 #ViralReels.mp3",
  "#video   बट क घर कब अइब ऐ मई  #Pawan Singh  Beta Ke Ghare  Bhojpuri Bhakti.mp3",
  "#Video  #Kheshari Lal Yadav  Kawan Fulawa Rath Sobhela  कवन फलव रथ सभल  Bhojpuri Devi Geet.mp3",
  "#VIDEO  #Pawan Singh  कब हग मईय क आरत  #Shilpi Raj  Ft. #Dimpal S  Bhojpuri Navratri Song.mp3",
  "#Video  #Pawan Singh  मई क आरत उतर  Maai Ke Aarti Utare  Shivani Singh  Bhojpuri Devi Geet.mp3",
  "#VIDEO  #Pawan Singh  वध वधन कछ जनल न हम  Priyanka Singh  Ft  Smriti Sinha  Devi Geet.mp3",
  "#Video  #Pawan Singh - हथ जर मग न मगनव ए मई - Khushboo Jain   #Bhojpuri Devi Geet 2023.mp3",
  "#Video  दलर मयरय  #Pawan Singh  Dulri Mayariya  Chandani Singh  Bhojpuri Devi Geet 2024 (1).mp3",
  "#Video  दलर मयरय  #Pawan Singh  Dulri Mayariya  Chandani Singh  Bhojpuri Devi Geet 2024.mp3",
  "#Video  मई क धमव दख क  #Pawan Singh  Mai Ke Dhamwa Dekhi Ke  Bhojpuri Navratri Song.mp3",
  "#Video  मई डल चढ चलल  #Pawan Singh  Mai Doli Chadhi Chalali Sevak Gharwa  Bhakti Songs.mp3",
  "#Video  मईय क गहन गढ़वन  #Pawan Singh  Maiya Ke Gahana Gadhawani  Bhojpuri New Devigeet 2023.mp3",
  "#video  मर मईय तह त पयर क समदर ह  #Pawan Singh Meri Maiya  Pawan Singh New Song.mp3",
  "#Video  ललक चनरय ओढ़ क  #Pawan Singh  #Akshara Singh  #New Bhojpuri Devi Geet.mp3",
  "#Video  शतल बयर  #Khesari Lal Yadav  Sital Bayar  Darbar Chali  Bhojpuri Bhakti Devi 2017.mp3",
  "#Video #Khesari Lal Yadav  #Priyanka Singh  Mati Ke Murti Se  Bhojpuri Bhakti Song.mp3",
  "#VIDEO #Khesari Lal Yadav New Song  बघव कहर  Priyanka Singh  Baghwa Kahar  Navratri New Song.mp3",
  "#Video #PawanSingh  आसर लगवल बन मई ह  Aasra Lagawle Bani Mai Ho  Navratri Video Song.mp3",
  "#Video #Song - #KhesariLalYadav क New भजपर दव गत - Chunariya Lele Aaiha - Navratri Songs.mp3",
  "#Video - अडहल क फल  #Pawan Singh, #Shivani Singh  Adahul Ke Phool  Bhojpuri New Devi Geet 2023.mp3",
  "#Video - कयलय धर बलS ह  #Pawan Singh  Koyaliya Dheere Bola Ho  Bhojpuri Devi Geet 2023.mp3",
  "#Video - बट क घर  #Pawan Singh New Devi Geet  Beta Ke Ghare  Bhakti Song 2017.mp3",
  "#Video मईय मर  Golu Gold  Maiya Mori  Pachara Bhojpuri Devi Geet 2023.mp3",
  "#VideoSong  #Pawan Singh  छट र मट नमय गछय I Choti Moti Nimiya Gachiya  Bhojpuri Bhakti.mp3",
  "#गउआ क परब कह उग ल सरज दव Malin Purube Kahe Hola Devi Darbar  #Pushpa rana.mp3",
  "Anjali bhardwaj  Jhuleli Ho Maiya Jhuleli  New Bhojpuri Bhakti song.mp3",
  "Arvind Akela Kallu - बचपन क सपरहट दव गत - मई ह तन आ जयत - Bhojpuri Devi Geet.mp3",
  "Baje Paijaniya Jab  Aaili Sato Bahiniya  Bhojpuri Devi Geet  Anjali Bhardwaj Bhakti Song, Sonotek.mp3",
  "BHARAT SHARMA VYAS - Bhojpuri Mata Bhajans  SAATO RE BAHINIYA  FULL AUDIO JUKEBOX  HamaarBhojpuri.mp3",
  "Chunri Mein Sunri Ke Roop Gore Gore  Bhojpuri Mata Bhajan  PAWAN SINGH  T-Series HamaarBhojpuri.mp3",
  "Full Video  मईय बर सकवर  #Karina Pandey  #Sovita Pandey  Maiya Bari Sukwar  Navratri Song.mp3",
  "HD VIDEO  Khesari Lal Yadav New Devi Geet  मईय क रपव कमल  Bhojpuri Navratri Songs.mp3",
  "HD धन बड़ धरत मईय - Mai Bolaweli  Khesari Lal Yadav  Bhojpuri Mata Bhajan @WaveMusicIndia.mp3",
  "Jagdamba Ghar Me  Swati Mishra  Mohit Musik  Bhojpuri Navratri Song 2025  Devi Geet.mp3",
  "Karpur Gauram Karunavtaram Bhojpuri Devi Bhajan  PAWAN SINGH  Maai De Da Chunariya Ke Chhaanv.mp3",
  "Khesari lal yadav क रल दन वल वदई दव गत  Bhojpuri Devi Geet 2019.mp3",
  "Lagela Nik Lagela  लगल नक लगल  anjali bhardwaj bhakti song  Devi Geet.mp3",
  "lale rang sindura ba.. lale rang purtaria... maiya ke tan par chunariya ho ki lale rangwa na.mp3",
  "Maa Sherawaliye  Akshay Kumar  Sonu Nigam  Sherawali Mata Bhajan  Chaitra Navratri Special Song.mp3",
  "MAAI KE MANDIR MANN BHAWAN LAAGELA  Bhojpuri Mata Bhajan  PAWAN SINGH  T-Series HamaarBhojpuri.mp3",
  "Maai Ke Mandir Mann Bhawan Laagela.mp3",
  "Maai Ke Mandir Me.mp3",
  "MAIYA KE AARTI  PAWAN SINGH  NEW DEVI GEET   HD FULL VIDEO SONG  मईय क आरत.mp3",
  "Maiya Meri Sherawali [Full Song] Maiya Ka Jawab Nahin.mp3",
  "MAIYA TERI JAI JAIKAAR  Lyrical  Arijit Singh Jeet Gannguli Gurmeet ChoudharyNavratri Special Song.mp3",
  "Mangal Ki Seva Sun Meri Deva  Narendra Chanchal  Kaali Mata Ki Aarti  Kaali Mata Bhajan.mp3",
  "Mann Bhabe Maiya Ke Chunariya Bhojpuri Devi Bhajan [Full Song] I Laagal Ba Darbar Mayee Ke.mp3",
  "MORI MAIYA KI CHUNAR UDI JAYE - मर मईय क चनर उड़ जय - SHAHNAZ AKHTAR - Ajaz Khan.mp3",
  "Nimiya ke Dadh Maiya  Swati Mishra Bhakti  Mohit Musik  Navratri Special Song.mp3",
  "Nimiya Ke Dhadh Maiya - नमय क डढ़ मईय - Jai Maa Ambey - Anu Dubey - Bhojpuri Mata Bhajan.mp3",
  "PAWAN SINGH  Durga Puja Ke Chanda 251 दरग पज क चद 251  Priyanka Singh  Bhojpuri Devi Geet.mp3",
  "Pawan Singh #New दव गत आगय  Lach Lach Lachke Dadhiya  Meri Maa  Devi Geet.mp3",
  "Pawan Singh New दव गत  Mela Ghume Aini  Meri Maa  Bhojpuri Devi Geet - #video.mp3",
  "Power Star Pawan Singh Latest Devi Geet 2024 - Lami Lami Kesh  Ft. Shweta Mahara  T-Series.mp3",
  "Ritesh Pandey Navratri Song - Mai Ke Duar Pe - Bhojpuri Devi Geet - Maa Durga Bhakti Song 2022.mp3",
  "Ritesh Pandey क नय दव गत - Ara Ke Mela - Nimiya Ke Gachhiya - Bhojpuri Devi Geet.mp3",
  "Tu Itni Door Kyun Hai Maa  Heart-Touching Mata Bhajan  Chaitra Navratri Day 2 Special.mp3",
  "VIDEO  Pawan Singh - सजल दरबर  Shivani Singh - Sajal Darbar  Bhojpuri New Devi Geet 2023.mp3",
  "Video - सवरग स चलल महरन  Ankush Raja New Song  Aastha Singh  Bhojpuri Devi Geet 2023.mp3",
  "Video-वधयचल मयरयRavindra Singh Jyotiवधयचल चलस वडय 2021New Bhakti Song.mp3",
  "अलग अलग रप म मई -Pawan Singh  Bhojpuri Mata Bhajan  मत क हट भजपर भजन.mp3",
  "आगय Gopal Rai क सबस पयर मत भजन  Bhojpuri Mata Bhajan.mp3",
  "आर आर कहर - Aare Aare Kohara - Pujali Maiya Sagari - Golu Gold - Bhojpuri Devi Geet.mp3",
  "आशन इनदर डसव - Jhuleli JHulanawa Hamar Maiya - Pawan Singh - Bhojpuri Devi Geet.mp3",
  "कब बनक Sato Kunwari- Singar Sajal Ba Mori Maiya Ke -Pawan Singh-Bhojpuri Mata Bhajan.mp3",
  "कल मई बड हमर गव   Pawan Singh  Singar Maiya Rani Ke  Bhojpuri Devi Geet 2023.mp3",
  "खसर क घर घर बजन वल भजन एक बर जरर सन - Mai Bolaweli - Khesari Lal - Bhojpuri Devi Geet.mp3",
  "खसर लल क भजन न सबक झमन पर कय मजबर - Mai Bolaweli - Khesari Lal - Bhojpuri Mata Bhajan.mp3",
  "गजब रप सहबन  Khesari Lal Yadav  Gajbe Roop Suhaban  Hathkadi  Bhojpuri Bhakti Song.mp3",
  "चमकल चदर Badaniya- Singar Sajal Ba Mori Maiya Ke -Pawan Singh-Bhojpuri Mata Bhajan.mp3",
  "जगदमब घर म दयर #परमपरक गव घर म गय जन वल दव गत #अन दब #Bhojpuri #VIDEO SONG.mp3",
  "जय जय म - Jai Jai Maa  Shobhela Darbar Sherawali Ke  Pawan Singh  Bhojpuri Mata Bhajan.mp3",
  "डल चढ़ चलल मईय - Doli Chadhi Chalali - Anu Dubey - He Jagtaran Maiya - Bhojpuri Devi Geet.mp3",
  "तर दर प O Meri Maiya - Singar Sajal Ba Mori Maiya Ke -Pawan Singh-Bhojpuri Mata Bhajan.mp3",
  "तर दरबर म मय खश मलत ह- Tere darbar mai maiya khushi milti hai -Lakhbir Singh Lakha.mp3",
  "दआर जगरत हई Duara Jagrata Hoi  Khesari Lal Yadav & Priyanka Singh.mp3",
  "दव गत  शरद सनह जगदब  नवरतर 2021 मत क भजन.mp3",
  "नक क नथनय  #Pawan Singh New Devi Geet Video  Sato Bahiniya Aili  New Bhojpuri Bhakti Gana.mp3",
  "नमय क डल मईय  Nimiya Ke Dal Maiya  Lahariya Luta Ae Raja Ji  Bhojpuri Bhakti Songs 2021.mp3",
  "नमय क डढ़ मईय  Nimiya Ke Dadh Maiya  Anu Dubey Devi Geet Pachra  Bhojpuri Devi Geet 2023.mp3",
  "नमय प मईय Lubha Gailey - Singar Sajal Ba Mori Maiya Ke -Pawan Singh-Bhojpuri Mata Bhajan.mp3",
  "नवरतर Special मर झल छट पड़ गई I  Meri Jholi Chhoti Pad Gai Re I NARENDRA CHANCHAL, HD Video.mp3",
  "नवरतर Special_ Maiya Ka Chola Hai Rangla with Lyrics,Devi Bhajan,LAKHBIR SINGH LAKKHA,मत भजन.mp3",
  "पवन सह क गन बजक - Pawan Singh Ke Bhajan Bajake - Akshara Singh - Bhojpuri Devi Geet.mp3",
  "बल कयलय भईल भर मईय -अजल भरदवज दवगत  - Anjali Bhardwaj Bhakti Song Bole Koyaliya.mp3",
  "मई क चनर चढ़वन  #Pawan Singh  #Akshara Singh  Mai Ke Chunari Chadhawani  #Bhojpuri Devi Geet.mp3",
  "रउर महम नरल - Jhula Jhuleli Sherawali  Arvind Akela Kallu Ji  Bhojpuri Devi Geet.mp3",
  "लग धरम क Bhaiyel Jata - Singar Sajal Ba Mori Maiya Ke -Pawan Singh-Bhojpuri Mata Bhajan.mp3",
  "सन र सगनय बद ब दकनय  Pawan Singh  Akshara - Sun Re Suganiya -New Bhojpuri Devi Geet 2022.mp3",
  "सबस हट दव गत - Kallu - Kawan Phoolawa - Nimiya Ke Chhau Me - Bhojpuri Devi Geet (1).mp3",
  "सबस हट दव गत - Kallu - Kawan Phoolawa - Nimiya Ke Chhau Me - Bhojpuri Devi Geet.mp3",
  "हमर मईय सनर  - Jhuleli JHulanawa Hamar Maiya - Pawan Singh - Bhojpuri Devi Geet 2024.mp3",
  "हव झर झर लगल - #VIDEO  Khesari Lal Yadav, Rani  Hawa Jhuru Jhuru Lagela  Devi Geet 2023 (1).mp3",
  "हव झर झर लगल - #VIDEO  Khesari Lal Yadav, Rani  Hawa Jhuru Jhuru Lagela  Devi Geet 2023.mp3"
])];
